apiVersion: v1 
kind: Pod 
metadata:
  name: sample-web 
spec:
  containers:
    - name: sample-cont 
      image: muralisocial123/citi-web-image:lates
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: '200m'
          memory: '250Mi'
        requests:
          cpu: '100m'
          memory: '100Mi'
